// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfertilityTreatmentSystem.DAL.Models;

public partial class Appointment
{
    public Guid AppointmentId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid DoctorId { get; set; }

    public Guid ServiceId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public string Status { get; set; }

    public string RejectReason { get; set; }

    public virtual User Customer { get; set; }

    public virtual User Doctor { get; set; }

    public virtual ICollection<MedicalRecord> MedicalRecords { get; set; } = new List<MedicalRecord>();

    public virtual TreatmentService Service { get; set; }
}