// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfertilityTreatmentSystem.DAL.Models;

public partial class Blog
{
    public Guid BlogId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedDate { get; set; }

    public Guid UserId { get; set; }

    public string BlogImage { get; set; }

    public virtual User User { get; set; }
}