// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfertilityTreatmentSystem.DAL.Models;

public partial class PatientRequest
{
    public Guid RequestId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid DoctorId { get; set; }

    public Guid ServiceId { get; set; }

    public string Note { get; set; }

    public DateTime RequestedDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual User Customer { get; set; }

    public virtual User Doctor { get; set; }

    public virtual TreatmentService Service { get; set; }
}