// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfertilityTreatmentSystem.DAL.Models;

public partial class Schedule
{
    public Guid ScheduleId { get; set; }

    public Guid CustomerId { get; set; }

    public Guid DoctorId { get; set; }

    public string SerivceName { get; set; }

    public DateTime? ScheduleDate { get; set; }

    public string Note { get; set; }

    public virtual User Customer { get; set; }

    public virtual User Doctor { get; set; }
}