// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InfertilityTreatmentSystem.DAL.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public int? Age { get; set; }

    public string PhoneNumber { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public string Avatar { get; set; }

    public virtual ICollection<Appointment> AppointmentCustomers { get; set; } = new List<Appointment>();

    public virtual ICollection<Appointment> AppointmentDoctors { get; set; } = new List<Appointment>();

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<MedicalRecord> MedicalRecordCustomers { get; set; } = new List<MedicalRecord>();

    public virtual ICollection<MedicalRecord> MedicalRecordDoctors { get; set; } = new List<MedicalRecord>();

    public virtual ICollection<PatientRequest> PatientRequestCustomers { get; set; } = new List<PatientRequest>();

    public virtual ICollection<PatientRequest> PatientRequestDoctors { get; set; } = new List<PatientRequest>();

    public virtual ICollection<Schedule> ScheduleCustomers { get; set; } = new List<Schedule>();

    public virtual ICollection<Schedule> ScheduleDoctors { get; set; } = new List<Schedule>();

    public virtual ICollection<TreatmentService> TreatmentServices { get; set; } = new List<TreatmentService>();
}